# title:              CHI YEN NGUYEN
<h1 class="site-title">
    <img src="chatbot.png" alt="CHI YEN NGUYEN" class="logo-icon" />
</h1>
# email:              your-email@example.com
description:        Exploring tomorrow’s intelligence, today
author:             Chi Yen Nguyen
baseurl:           ""
url:               "https://chinguyen27.github.io/"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    Chi Nguyen
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username: Chi Nguyen

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
